### ISSUE TITLE
Logging Abstraction

### ISSUE THREAD

**Issue by thomasbiesaart** [tulskiy/jkeymaster#24]
Hey, 
I am interested in using this library for my project, however I would like to have to logging also looped through my logging system of choice automatically using slf4j.

If I'd make you a pull request where I replace all the JUL stuff with slf4j, would you be willing to merge it?

**Comment by tulskiy** [comment]
hi, yes, sure

**Comment by tulskiy** [comment]
ok, I've merged it and will prepare a snapshot for you shortly

**Comment by thomasbiesaart** [comment]
Thank you very much sir, happy new year by the way

**Comment by tulskiy** [comment]
1.2-SNAPSHOT published. will you need a version on maven central?

**Comment by thomasbiesaart** [comment]
I generally use jcenter but if you're hosting on a different repo until you have a release then I can use that one. I don't expect to have a release for my project within 6 months anyway

**Comment by tulskiy** [comment]
I use sonatype oss repo for snapshots. Anyways, I've released version 1.2 to maven central.
