### ISSUE TITLE
Hotkey events don't return to system (Windows)

### ISSUE THREAD

**Issue by ancient-behemoth** [tulskiy/jkeymaster#26]
Hotkey events captured by this code are not returned to system. This causes two drawbacks for me:
1) Same hotkeys used in other aplications running on OS are not working. For example when I register "Ctrl + Tab" hotkey in my appliacation, this shortcut won't work for Internet browsers anymore, where it normally switch to next tab.
2) I can't use released hotkeys alongside with pressed (default) ones. For example when I implement:
`provider.register(KeyStroke.getKeyStroke("control PERIOD"), listener);
provider.register(KeyStroke.getKeyStroke("control released PERIOD"), listener2);`
or by other way to do this
`provider.register(KeyStroke.getKeyStroke(KeyEvent.VK_PERIOD, InputEvent.CTRL_MASK), listener);
provider.register(KeyStroke.getKeyStroke(KeyEvent.VK_PERIOD, InputEvent.CTRL_MASK, true), listener2);`
only pressed event will occur, released will never happen. (becouse pressed event was "consumed"/not returned to OS) When I register only second (released) hotkey, without first one (pressed), it works fine, but usually you want to use released hotkey alongside with pressed. (when you want something to keep happening for period of time between pressing and releasing keyboard key) Unfortunately I can't implement something like this with this code.

I analized your code and I thought that code causing this behaviour is line 58 in class WindowsProvider (I'm using Windows OS):
`while (PeekMessage(msg, null, 0, 0, PM_REMOVE)) {`
According to [PeekMessage function description](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644943(v=vs.85).aspx), PM_REMOVE value (0x0001) removes message from the queue, while PM_NOREMOVE (0x0000) don't. So I tried to use PM_NOREMOVE value there, but this causes message to be processed by this code in endless loop. But even if I change while to if, this didn't cause same shortcut in other application to work... so I guess either it's not what I'm looking for, or I did something wrong. (probably second one, as other shortcuts in my application after using first one also don't work - as loop is processing first one all the time) Or maybe I just have to manually remove message from the queue and it has nothing to do with other applications? Anyway I have no success with trying to implement PM_NOREMOVE value. I also tried to use GetMessage instead of PeekMessage, but it works differently and I didn't manage to implement similar behaviour to your code.

I'm not asking to enable returning hotkey events to system, as it looks like a lot of work, but maybe you could at least give me some pointers or ideas about how could I implement this to work?

Thank you in advance for your help.

**Comment by tulskiy** [comment]
Hi, I do not handle isOnKeyRelease flag in KeyStroke anywhere in the library.
The trick is to add MOD_KEYUP flag when registering hotkey. This way windows will send WM_HOTKEY event on both key press and key release. Check out my latest commit, I've added some handling for MOD_KEYUP on windows.

However, I do not have windows to test this. Most probably in WindowsProvider loop you will need to add some extra checks after receiving message from PeekMessage to prevent it from firing release hotkey on keypress. Something like:

    if (hotkey.keystroke.isOnKeyRelease() && msg.lParam & MOD_KEYUP == MOD_KEYUP)

let me know if it works for you

**Comment by schuettec** [comment]
> Hotkey events captured by this code are not returned to system. [...] Same hotkeys used in other aplications running on OS are not working.

What about this issue? Is there a chance to not consume the key event?
In my case I want to register CTRL+C to build a Mulit-item-Clipboard-Thing. But when I register CTRL+C the original copy action in other applications is not triggered any more.

**Comment by tulskiy** [comment]
@schuettec, `RegisterHotKey` api does not allow that. You will need a low level keyboard hook like https://github.com/kwhat/jnativehook

**Comment by ancient-behemoth** [comment]
@tulskiy thank you for quick reply. Unfortunately after your last commit I can't even register such hotkey:
`WARNING: Could not register hotkey: HotKey{shift ctrl released 1}`
It's log from line 106 in class **WindowsProvider**. So it looks like in this case function _RegisterHotKey_ failed. Any ideas what could cause that? (I don't have much knowledge about using native libraries)

Thank you in advance for your answer.

**Comment by tulskiy** [comment]
turns out, MOD_KEYUP is only for win mobile and is not supported on regular windows. I'll revert that code.

try using a low-level keyboard hook as recommended above. I might want to implement a similar thing with jna some time, but I wouldn't count on that.

**Comment by ancient-behemoth** [comment]
OK, I'll try that low-level keyboard hook you mentioned. Thanks for info.

**Comment by tulskiy** [comment]
what you can also do is remove `modifiers |= MOD_NOREPEAT;`. This way you will keep receiving the event while hotkey is pressed. You can then start a timer for, say 100ms, and reset it when you receive a hotkey event. Once you stop receiving events, timer will have a chance to go off and it will mean that a hotkey is released :)

not really useful, but could be a fun exercise.
