### ISSUE TITLE
Exception re incorrect event thread when running with JavaFx

### ISSUE THREAD

**Issue by benjwarner** [tulskiy/jkeymaster#27]
Hi there!
Thanks for the library.

Have been attempting to integrate with JavaFx.  Specifically the version that ships with java 8.

It appears that between Swing and JavaFx, the method of running Runnable's on the event thread has changed. 

From Provider.java, the line:
`SwingUtilities.invokeLater(event);`

Will create an exception in JavaFx which looks like this:

`Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = AWT-EventQueue-0`

However updating the line to this:
`javafx.application.Platform.runLater(event);`

....works for the version of JavaFx I've been using.

I found some info about it here on [stackoverflow](http://stackoverflow.com/questions/12984310/javafx-response-to-swingutilities-invokelater)

If you wanted to integrate with JavaFx, I'm not sure what the best method interface would be.  Maybe a new getCurrentProvider() method which takes an enum.  e.g.
`Provider provider = Provider.getCurrentProvider(UseApplicationThread.JAVA_FX);
`

**Comment by mgarin** [comment]
The best solution is probably avoid using framework-related threads since you can always redirect the action into any thread you want at any time from the hotkey listener.

**Comment by benjwarner** [comment]
Yes, that's a very good point.  Thanks very much.

Example for completeness:

```
        Provider provider = Provider.getCurrentProvider(false);
        provider.register(KeyStroke.getKeyStroke(hotkeyCombination), hotKey -> {
            Platform.runLater(() -> {
                //do work
            });
        });
```
