### ISSUE TITLE
How can I pass fired keyboard events to other applications without completely consuming it?

### ISSUE THREAD

**Issue by ahmedmohiduet** [tulskiy/jkeymaster#30]
I am struggling to implement  'enable/disable' hotkeys features in my hotkey application.
So far  I'm trying to achieve is rely on an 'disabled' flag and achieve something like:
```
OnHotKey:
if(disabled){
pass this key to the rest of the apps;
do nothing and return;
}
```
Or else can I can have my own implementation something like:
```
provider.pause();
provider.resume();

```
Would love to submit a PR, can you guide me a little as in what classes/methods to play around to implement this feature ?

**Comment by tulskiy** [comment]
Hi,

As long as the hotkey is registered, no other apps will receive it. If you
want to stop receiving hotkeys, there is a reset() method in the Provider.
And to enable, register them all again.

**Comment by ahmedmohiduet** [comment]
Hi tulsky,

Thanks for the prompt response. Unfortunately I am looking to have one of my hot keys still enabled even on provider.reset(). F8 in my case enabling/disabling my hotkey app . Can I have more than one  provider instances? Would it be ok at run time?

**Comment by tulskiy** [comment]
I don't think having multiple providers will work. There's a lot of native
code synchronization going on.

It should be possible to modify the api to unregister individual hotkeys.
If you return the HotKey object when registering, you can then pass it to
the provider to unregister. I'm not sure why I didn't implement it this way
at first, maybe there were some limitations.

You can also re-register your f8 hotkey right after resetting. That would
be the simplest solution for you.

**Comment by ahmedmohiduet** [comment]
got it. goting for a provider.unregister(Specific_Hot_Key).
