### ISSUE TITLE
Linux xcb problems

### ISSUE THREAD

**Issue by nikkiii** [tulskiy/jkeymaster#8]
Well I guess it wasn't solved, key binding works however this problem still occurs.

The JVM outputs this:

```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: ../../src/xcb_io.c:273: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted
```

Was tested on Ubuntu 11.10 x86_64 again...
Stops the whole program after a random key press (a hotkey of course, just it doesn't happen every time)

Hopefully this is a bit more clear than my other issue :p

**Comment by nichenghyx** [comment]
Hello ,I have the same problem, but I can't solve it，I used raspiberry,Debian systerm.
